version: '3.1'

services:
  db:
    image: postgres:15
    container_name: odoo-db
    environment:
      - POSTGRES_DB=wilkinsdbtwo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - odoo-net

  odoo:
    image: odoo:18
    container_name: odoo-app
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    user: "0"
    volumes:
      - ./odoo-data:/var/lib/odoo
      - ./odoo-data/addons:/mnt/extra-addons
    networks:
      - odoo-net

networks:
  odoo-net:
    driver: bridge
